### ISSUE TITLE
Transfer repo to ckan organization

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-envvars#11]
As this extension is used in the official Docker images it is pretty critical. @pdelboca @avdata99 what do you think about moving it to the ckan organization? I have a PR ready to fix compatibility with CKAN 2.11 but I don't have permissions on this repo to create a new release etc.

**Comment by pdelboca** [comment]
@amercader done! :)

**Comment by wrinklenose** [comment]
The latest "release" of version 0.0.6 broke our docker ckan build for ckan 2.8.4.

The missing official release boosted the confusion. Could you please provide an official release including a matching changelog?

**Comment by amercader** [comment]
@wrinklenose can you provide a stack trace or describe the issue you found with the new release?

**Comment by wrinklenose** [comment]
Sure. I just thought it wouldn't be of interest cause it happens for the old ckan version 2.8.4 which build we had to manipulate several times in the past.

It seemed, that the list of installed plugins which we provide over envvars are not longer taken over to the production.ini inside the image.

The docker build runs without any problem but during startup there happen several issues which prevent ckan to start correctly:

> SyntaxError: invalid syntax
> 2024-09-10 14:36:38,252 INFO spawned: 'ckan-worker' with pid 2596
> OOPS ! failed loading app in worker 2 (pid 2591) :( trying again...
> DAMN ! worker 2 (pid: 2591) died :( trying respawn ...
> Respawned uWSGI worker 2 (new pid: 2597)
> OOPS ! failed loading app in worker 1 (pid 2592) :( trying again...
> DAMN ! worker 1 (pid: 2592) died :( trying respawn ...
> Respawned uWSGI worker 1 (new pid: 2598)
> Loading paste environment: config:/srv/app/production.ini
> Loading paste environment: config:/srv/app/production.ini
> 2024-09-10 14:36:39,255 INFO success: ckan-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2024-09-10 14:36:40,643 INFO  [ckan.config.environment] Loading static files from public
> 2024-09-10 14:36:40,746 INFO  [ckan.config.environment] Loading static files from public
> 2024-09-10 14:36:40,829 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
> 2024-09-10 14:36:40,916 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
> Traceback (most recent call last):
>   File "/usr/bin/paster", line 11, in <module>
>     load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
>   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
>     invoke(command, command_name, options, args[1:])
>   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
>     exit_code = runner.run(args)
>   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
>     result = self.command()
>   File "/srv/app/src/ckan/ckan/lib/cli.py", line 2576, in command
>     self._load_config()
>   File "/srv/app/src/ckan/ckan/lib/cli.py", line 330, in _load_config
>     self.site_user = load_config(self.options.config, load_site_user)
>   File "/srv/app/src/ckan/ckan/lib/cli.py", line 237, in load_config
>     load_environment(conf.global_conf, conf.local_conf)
>   File "/srv/app/src/ckan/ckan/config/environment.py", line 115, in load_environment
>     p.load_all()
>   File "/srv/app/src/ckan/ckan/plugins/core.py", line 140, in load_all
>     load(*plugins)
>   File "/srv/app/src/ckan/ckan/plugins/core.py", line 154, in load
>     service = _get_service(plugin)
>   File "/srv/app/src/ckan/ckan/plugins/core.py", line 256, in _get_service
>     return plugin.load()(name=plugin_name)
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
>     return self.resolve()
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/srv/app/src/ckanext-envvars/ckanext/envvars/plugin.py", line 78
>     log.info(f"Loading new plugin: {plugin}")
> 

The workaround was to nail the envvars version to the old 0.0.4, through which ckan builds and starts up without any issue.

**Comment by amercader** [comment]
@wrinklenose got you. This error is caused by a Python 2.7 compatibility issue

```
  File "/home/adria/dev/pyenvs/ckan-28/src/ckanext-envvars/ckanext/envvars/plugin.py", line 78
    log.info(f"Loading new plugin: {plugin}")
                                           ^
SyntaxError: invalid syntax
```

We don't support Python 2.7 or CKAN 2.8, I've added that to the release notes for ckanext-envvars
